### ISSUE TITLE
nativescript-facebook not found

### ISSUE THREAD

**Issue by wolfgangmeyers** [NativeScript/nativescript-facebook#11]
Hello, I entered the command as it was specified in the readme file, and I got this error:
```
$ tns plugin add nativescript-facebook
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "install" "nativescript-facebook" "--save"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/nativescript-facebook
npm ERR! 404
npm ERR! 404  'nativescript-facebook' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by wolfgangmeyers** [comment]
this however seems to work: `$ tns plugin add nativescript-facebook-login`

**Comment by wolfgangmeyers** [comment]
I was able to work around by cloning this repository, moving `src` out and renaming it to `nativescript-facebook`, running `tns add plugin <relative path to local copy>`, and then manually running `tsc` to compile the package. I've added the FacebookLoginButton in my app component but nothing shows up. I'm also seeing some errors when the app loads:
```
Falling back to loading access token from NSUserDefaults because of simulator bug
Falling back to storing access token in NSUserDefaults because of simulator bug
Falling back to loading access token from NSUserDefaults because of simulator bug
Falling back to storing access token in NSUserDefaults because of simulator bug
Falling back to loading access token from NSUserDefaults because of simulator bug
Falling back to storing access token in NSUserDefaults because of simulator bug

Normal message received by listener connection. Ignoring.
Could not successfully update network info during initialization.
```
Some digging on google shows that others have hit these errors with the ios facebook sdk, and there are some suggestions on how to fix. Unfortunately it's a black box to me, since I'm using this wrapper over the sdk. Any ideas?

http://stackoverflow.com/questions/43446404/could-not-successfully-update-the-network-info-during-initialization-xcode-error
http://stackoverflow.com/questions/41033776/falling-back-to-loading-access-token-from-nsuserdefaults-because-of-simulator-bu

**Comment by angeltsvetkov** [comment]
He @wolfgangmeyers. The plugins is still not published to npm. It will be soon. That's why you hit this error.

**Comment by wolfgangmeyers** [comment]
I will try running those and let you know if I hit any issues.

**Comment by angeltsvetkov** [comment]
The nativescript-facebook plugin has been published in npm. You shoul no more experience this issue. I am going to close it.

**Comment by wolfgangmeyers** [comment]
FYI while other features (like graph api) are in development, it might be worth mentioning that it is straightforward to use the available [http client](https://docs.nativescript.org/cookbook/http) to make authorized calls to the graph api, passing in the token retrieved by the login by appending `?access_token=<token here>`.
