### ISSUE TITLE
Share facebook post to owner facebook page

### ISSUE THREAD

**Issue by thiepwong** [NativeScript/nativescript-facebook#128]
There is no share and like features in the nativescript-facebook plugin. It'll be better if we can share and like some post to the facebook page. 
I known the Facebook removed the api that post something to page, but they  allowed we share or like through their native dialog.

Thanks for all!

**Comment by VladimirAmiorkov** [comment]
Duplicated of this issue https://github.com/NativeScript/nativescript-facebook/issues/73

**Comment by thiepwong** [comment]
I am coding the share feature, it is ok on android. I'll commit it to
github.
