### ISSUE TITLE
CALL_AND_RETRY_LAST Allocation failed

### ISSUE THREAD

**Issue by samehhady** [NativeScript/nativescript-facebook#14]
The build process is eating my memory, it keeps failing in tsc && ngc
I've tried to increase max-old-space-size but didn't help.
Any ideas?

**Comment by angeltsvetkov** [comment]
This is caused by one of the latest commits. It is not in version 1.0.1. 
Try to change build script in src/package.json from tsc&ngc to tsc only.

**Comment by samehhady** [comment]
Thx! this fixed my issue, everything is working now :)
