### ISSUE TITLE
conflict with barcode scanner

### ISSUE THREAD

**Issue by zzzxtreme** [NativeScript/nativescript-facebook#141]
My app uses nativescript-barcode-scanner which uses zxing.

After I added nativescript-facebook plugin, I get this error

"Program type already present: com.google.zxing.BarcodeFormat"

Curious to know if facebook plugin uses zxing ?

Wondering if anyone has any solution? any help would be greatly appreciated.

**Comment by elena-p** [comment]
Hi @zzzxtreme,

nativescript-facebook plugin doesn't include ZXing library explicitly. However, it wraps the native Facebook SDK for Android, which includes the ZXing library as a dependency. 

It seems that the nativescript-barcodescanner plugin includes the ZXing library in their own distributed library and the two cannot get merged.

You can add these lines to your app.gradle file in app/App_Resources/Android, as suggested in a similar [issue](https://github.com/EddyVerbruggen/nativescript-barcodescanner/issues/108).

```
configurations {
    compile.exclude group: 'com.google.zxing'
}
```

**Comment by zzzxtreme** [comment]
thanks you. very much appreciated !
