### ISSUE TITLE
Github repo updated but not published to npm

### ISSUE THREAD

**Issue by lin-brian-l** [NativeScript/nativescript-facebook#143]
My team and I have been PR #139 and were excited to see that it was merged to `master`, but the npm registry has not been updated yet. Is there a timeline for when this will happen?

EDIT: I meant to say that we have been *following* PR #139, we did not have any involvement with the PR. Sorry for any confusion!

**Comment by elena-p** [comment]
Hi @lin-brian-l,

Once again, thank you and your team for the contribution!
We have reviewed the code and our CI tests have passed, but our QAs still need to approve the new functionality and add some tests for it. 
You can track the status of the Share feature issue [here](https://github.com/NativeScript/nativescript-facebook/issues/73). It will be updated once a new version is published in npm. A rough estimate is that we will have it till the end of the week.

**Comment by lin-brian-l** [comment]
@elena-p Thank you for the continued support you and your team put into this plugin :)
