### ISSUE TITLE
Expose functions to track app events in facebook analytics

### ISSUE THREAD

**Issue by Chandu-Bantupalli** [NativeScript/nativescript-facebook#147]
I am trying to use the functions of appevents package of the Facebook SDK in my nativescript Application. Tried to use the nativescript-facebook plugin. But could not find a solution. Could anyone help please. Thanks in advance

**Comment by elena-p** [comment]
Hi @Chandu-Bantupalli,

Please update the issue's title and description to better describe the feature you are looking for or the problem you have faced.

Currently the plugin provides the following [features](https://github.com/NativeScript/nativescript-facebook#features). 

What type of events do you wish to track and what are the functions you are missing? Do you think that such functionality should be included in this or in a separate plugin?

**Comment by Chandu-Bantupalli** [comment]
As we have AppEventsLogger in the Facebook Android SDK which extends appevents package, this can log events occurring in the app into facebook analytics. 
I could not find such functions in the nativescript-facebook plugin. I have tried to make changes in the existing plugins but could not make it execute.
please anyone could help me

**Comment by elena-p** [comment]
Hi @Chandu-Bantupalli,

I have marked the issue as a feature request, but cannot commit to a time when it will be available. 

Meanwhile, we love pull requests and we would highly appreciate it, if you decide to implement the analytics functionality. You can create a manager (check login-manager for example) and implement it using AppEventsLogger for android and FBSDKAppEvents for ios.

**Comment by claudiojgonzalez** [comment]
Hi @DimitarTodorov, do you have any update regarding this change?
Thanks!!

**Comment by DimitarTodorov** [comment]
Implemented with the 4.1.0 release of nativescript-facebook which is now published in npm. 
https://github.com/NativeScript/nativescript-facebook/releases/tag/v4.1.0
