### ISSUE TITLE
is it possible to make login event create user name and user ID in firebase firestore

### ISSUE THREAD

**Issue by job111** [NativeScript/nativescript-facebook#155]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?

- Android versions 
- emulator or device. What type of device?

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by elena-p** [comment]
Hi @job111,

 This plugin wraps some of the functionalities provided by the native Facebook SDK for Android and iOS. For any Firebase related operations you could use [this Firebase plugin](https://market.nativescript.org/plugins/nativescript-plugin-firebase), which enables you to use [Firestore](https://github.com/eddyverbruggen/nativescript-plugin-firebase/blob/HEAD/docs/FIRESTORE.md). 

 Here is how you can get facebook user's name and id:

1. On login, in the response, you receive the access token of the user (you can check it in the [demo app](https://github.com/NativeScript/nativescript-facebook/blob/master/demo/app/login-view-model.ts#L42)). 

1. You can then use the access token to get facebook's user name and id as shown here in the [demo app](https://github.com/NativeScript/nativescript-facebook/blob/master/demo/app/home-view-model.ts#L17).
