### ISSUE TITLE
Error when requiring nativescript-facebook

### ISSUE THREAD

**Issue by csaggo** [NativeScript/nativescript-facebook#17]
Im running {N} 2.5.0 platform. Im trying to use the Plugin for facebook login. But it fails immediately when i require the module with the following errror:

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

TypeError: view_1.Property is not a constructor
File: "file:///data/data/.. my app ../files/app/tns_modules/nativescript-facebook/login-button.common.js, line: 26, column: 26

StackTrace: 
	Frame: function:'', file:'file:///data/data/... my app .../files/app/tns_modules/nativescript-facebook/login-button.common.js', line: 26, column: 27
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/... my app .../files/app/tns_modules/nativescript-facebook/login-button.js', line: 13, column: 29
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/... my app .../files/app/tns_modules/nativ

my Code in app.android.js before application.start:

```
var nsFacebook = require('nativescript-facebook');

application.on(application.launchEvent, function (args) {
    nsFacebook.init("... my App Id ...");
});
```

Did I miss something?

**Comment by radeva** [comment]
Hi @csaggo,

The plugin is compatible with NativeScript 3.0 only. You need to migrate your application to NativeScript 3.0 in order to use it. To ease this process you can use our [migration guide](https://github.com/NativeScript/NativeScript/wiki/Migrating-Plugins-to-NativeScript-3.0).

**Comment by csaggo** [comment]
Thank you for the Info @radeva 
thats a bummer, guess I was decepted by the "Initial with nativescript 2.5 support." commits in the repo :-)
