### ISSUE TITLE
Cannot build in ios

### ISSUE THREAD

**Issue by preethijayanthi** [NativeScript/nativescript-facebook#179]
When I am building my app in IOS, It is showing the following errors,
`/platforms/ios/Pods/FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKShareDialog.m:502:9: error: unknown type name 'FBSDKBridgeAPICallbackBlock';
      did you mean 'FBSDKBridgeAPIResponseBlock'?`

`/platforms/ios/Pods/FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/FBSDKShareDialog.m:513:52: error: no visible @interface for
      'FBSDKApplicationDelegate' declares the selector 'openBridgeAPIRequest:useSafariViewController:fromViewController:completionBlock:'`

I  have also updated the pod files but the error remains the same.

**Comment by DimitarTodorov** [comment]
Hello, @preethijayanthi 

Can you share exact steps to reproduce the issue that you are describing. I've tested all our demos in the repo and they work fine. Can you share more details like iOS version, tns version and what kind of application you are running (Typescript/Angular/Vue-js).

**Comment by preethijayanthi** [comment]
I am running in angular. I am running through the command `tns run ios` . while building xcode, I am receiving issue. I am using tns verion - 5.0.0.

**Comment by DimitarTodorov** [comment]
Hi @preethijayanthi,

You can try updating the tns to 5.3.0(latest official version) and update your pod repos if needed with the command ```pod repo update```. Then clean your app - remove the ./node_modules and ./platforms folders and try to build the app again. If the issue persist, please send us an example where we can reproduce it.
