### ISSUE TITLE
[iOS] Demo-Vue continue with custom login crashes the app

### ISSUE THREAD

**Issue by DimitarTodorov** [NativeScript/nativescript-facebook#183]
Demo-Vue app crashes when tap on "Continue with Facebook (custom)" button.

### Which platform(s) does your issue occur on?
- iOS

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.3.0
- Cross-platform modules: 5.3.0
- Runtime(s): iOS: 5.3.0 
- Plugin(s): nativescript-facebook: 3.0.0
- ```pod --version``` : 1.5.0
### Please, tell us how to recreate the issue in as much detail as possible. 
1. Open the repo and run the demo-vue ```cd demo-vue && tns run ios/android --bundle```
2. Tap on "Continue with Facebook (custom)" button
Actual: The app crashes.
Expected: A modal window should be loaded with facebook login form.

### Is there any code involved? 
Demo-vue app in the repo

**Comment by tbozhikov** [comment]
same as https://github.com/NativeScript/nativescript-facebook/issues/184
