### ISSUE TITLE
Share button is disabled

### ISSUE THREAD

**Issue by mandrag0ra** [NativeScript/nativescript-facebook#194]
### Which platform(s) does your issue occur on?
- iOS
- iOS 12.2
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.4.0
- Cross-platform modules: 5.4.1
- Runtime(s): 5.4.0
- Plugin(s): 
```
...
 "dependencies": {
    "events": "^3.0.0",
    "htmlparser2": "^3.10.0",
    "lodash.isempty": "^4.4.0",
    "lodash.merge": "^4.6.1",
    "nativescript-background-fetch": "^1.2.1",
    "nativescript-cardview": "^3.1.1",
    "nativescript-facebook": "^3.0.1",
    "nativescript-platform-css": "^1.6.7",
    "nativescript-social-share": "^1.5.2",
    "nativescript-sqlite": "^2.3.3",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-listview": "^6.2.0",
    "rss-parser": "^3.6.2",
    "tns-core-modules": "^5.4.1",
    "url-parse": "^1.4.4"
  },
  "devDependencies": {
    "ajv": "^6.10.0",
    "nativescript-dev-webpack": "^0.24.0",
    "nativescript-worker-loader": "^0.9.5",
    "ts-loader": "^5.3.3",
    "typescript": "^3.3.4000"
  }
...
```

### Please, tell us how to recreate the issue in as much detail as possible. 
I did not find a proper way to reproduce the error.
The demo app is working fine. But even if I copy/paste the code from the demo app in my project, and If I'm logged in Facebook (via Nativescript-facebook login), the share button is disabled (gray).
"Open share dialog (link)" button is not working either.
Do you have any advise please ?

N.B: FBSDKShareKit (4.38.1)

**Comment by elena-p** [comment]
Hi @mandrag0ra,

Could you check whether you have configured your app for iOS as described [here](https://github.com/NativeScript/nativescript-facebook/blob/master/README.md#ios)? 
If the problem still persist, you could try to isolate the issue in a smaller app so that we are able to review it and provide you further assistance.

**Comment by mandrag0ra** [comment]
Hi @elena-p,

I'm sorry. Indeed, I have missed this.
Thank you.
