### ISSUE TITLE
Given URL is not allowed Android

### ISSUE THREAD

**Issue by darrenkhouston** [NativeScript/nativescript-facebook#220]
### Which platform(s) does your issue occur on?
- Android Only
- Android 9 API 28
- Emulator - Pixel 2

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.2.0
- Cross-platform modules: 6.2.0
- Runtime(s): 6.2.0 on Both
- Plugin(s): `
"dependencies": {
    "@exeleon/nativescript-svg": "^1.0.1",
    "@vue/devtools": "^5.0.6",
    "nativescript-facebook": "^4.2.1",
    "nativescript-fonticon": "^2.0.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-loading-indicator": "^2.5.2",
    "nativescript-socketio": "^3.2.1",
    "nativescript-statusbar": "^5.0.0",
    "nativescript-toasty": "^1.3.0",
    "nativescript-ui-sidedrawer": "^7.0.0",
    "nativescript-vue": "^2.4.0",
    "nativescript-vue-devtools": "^1.2.0",
    "nativescript-vue-navigator": "^0.2.0",
    "nativescript-webview-interface": "^1.4.3",
    "nativescript-windowed-modal": "^6.0.0",
    "tns-core-modules": "^6.2.0",
    "vuex": "^3.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "nativescript-dev-webpack": "^1.0.0",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "vue-loader": "^15.4.0"
  }
`

When I am logging into Facebook on iOS, the application takes me straight to Facebook, lets me login then sends me back to the app, no issues. On Android, when I click my button to login to Facebook, the form pulls up, I can enter my email and password, then on the next screen I get an error of "Given URL is not allowed by the Application Configuration: One or more of the given URLs is not allowed by the App's settings. To use this URL you must add a valid native platform to your App's settings."

My app is still in development mode with Facebook, and I have a place for a return URL, but since this is native to the Android system, I have no clue what the URL should be.

**Error Screenshot from Android**
<img width="423" alt="Screen Shot 2019-11-11 at 3 29 48 PM" src="https://user-images.githubusercontent.com/5124378/68623343-e6fbf200-0499-11ea-955f-70641ea9d245.png">

**Works fine on iOS**
<img width="423" alt="Screen Shot 2019-11-11 at 3 29 48 PM" src="https://user-images.githubusercontent.com/5124378/68623374-f67b3b00-0499-11ea-80a9-ab589d7f407c.png">

**Comment by darrenkhouston** [comment]
I fixed this issue. You are required to add the Android Platform to your Facebook App in order to get it to work. I just used my apps `org.nativescript.whatever` URL to get it to bypass the error. Would be good to know this in the documentation for testing purposes. My app is not live, so this would make sense to know while you are setting up the application.

![This is where you add the Android Platform to your Facebook App](https://user-images.githubusercontent.com/5124378/68801505-d4142980-0621-11ea-8452-78ade29dd642.png)

**Comment by laylashams5** [comment]
I added this is AndroidMainfest.xml 

        <activity android:name="com.facebook.CustomTabActivity" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity> and then it's work!

**Comment by moltedopablo** [comment]
Hi, in my case I followed the instructions in "Use cases -> customize -> Quick Start" of Facebook dashboard, the problem was the key hash located in `debug.keystore` 

After completing some steps in the wizard above and running the following, it worked:
```bash
keytool -exportcert -alias androiddebugkey -keystore android/app/debug.keystore | openssl sha1 -binary | openssl base64
```
