### ISSUE TITLE
Could not find com.facebook.android:facebook-core:5.11.1.

### ISSUE THREAD

**Issue by JuanDeLeon** [NativeScript/nativescript-facebook#221]
### Which platform(s) does your issue occur on?
- Android

### Please, provide the following version numbers that your issue occurs with:
6.2.0

### Please, tell us how to recreate the issue in as much detail as possible. 
Trying to build Android project, results in the above error.

The dependency needs to be updated, as mentioned in this issue:
https://github.com/facebook/facebook-sdk-for-unity/issues/357

**Comment by isojtouano** [comment]
Having the same issue

**Comment by isojtouano** [comment]
As a temporary fix you can add "implementation 'com.facebook.android:facebook-android-sdk:5.11.0'" to your dependencies in your app.gradle file

**Comment by elena-p** [comment]
Hi @JuanDeLeon, @isojtouano, there was an issue in v5.11.1 and v5.11.2 with a fix is released. Android builds passed for our latest test run - https://travis-ci.org/NativeScript/nativescript-facebook.
