### ISSUE TITLE
How to use api calls, like get public profile using angular 2?

### ISSUE THREAD

**Issue by 98falcon** [NativeScript/nativescript-facebook#23]

**Comment by angeltsvetkov** [comment]
@98falcon I will update the demo apps in order to cover this scenario and will let you know.

**Comment by 98falcon** [comment]
@angeltsvetkov thank you !

**Comment by angeltsvetkov** [comment]
@98falcon How about the updated README and demo apps. Also take a look at the new way you define your log in  and log out logic. As @ADjenkov proposed we introduced events instead of properties. It is still not published in npm so any feedback will be appreciated.

**Comment by angeltsvetkov** [comment]
I hope the README update brings more clarity now regarding how to call Facebook Graph API once you retrieve access token. I will close the issue. 
Please feel free to reopen the issue if you still have any troubles.

**Comment by 98falcon** [comment]
here's an easier way to get the public profile with only one http request
`http.getJSON(config + "/me?fields=id,first_name,last_name,picture,email&access_token=" + this.accessToken).then((res)=>{ console.log(res)}));`

**Comment by obadi2021** [comment]
dfgdfg
