### ISSUE TITLE
facebook  login nativescript angular App

### ISSUE THREAD

**Issue by nelsonwilliam11** [NativeScript/nativescript-facebook#24]
hello 
i want the Facebook login to navigate to my app homepage 
i tired route navigation but it does not work
any sort of help is needed ASAP

**Comment by theqaangel** [comment]
Cool. I will update the demo apps in order to cover this scenario.

**Comment by angeltsvetkov** [comment]
@nelsonwilliam11 Cool. I will update the demo apps in order to cover this scenario and will let you know.

**Comment by nelsonwilliam11** [comment]
Alright thanks

**Comment by ADjenkov** [comment]
@nelsonwilliam11  I guess you want to navigate to home page when the (login) callback is executed? 
I can suggest you a temporary workaround/hack.

Add static property to your `routerExtensions` in the component that you are navigating from.And then call its `navigate` from the login callback.

![image](https://cloud.githubusercontent.com/assets/5860190/26295116/eabeb300-3ed0-11e7-9200-3ba2675f383c.png)

**Comment by angeltsvetkov** [comment]
@nelsonwilliam11  How about the updated README and demo apps. Also take a look at the new way you define your log in  and log out logic. As @ADjenkov proposed we introduced events instead of properties. It is still not published in nom so any feedback will be appreciated.

**Comment by nelsonwilliam11** [comment]
Yeah thanks alot
But I don't know why not tells me "Names pace has no exported member 'Login
eventData'"

**Comment by angeltsvetkov** [comment]
Sorry, could you elaborate a little bit more? I didn't get what you said.

**Comment by nelsonwilliam11** [comment]
onLogin(eventData: Facebook.LoginEventData) {
        if (eventData.error) {
            alert("Error during login: " + eventData.error);
        } else {
            appSettings.setString("access_token", eventData.loginResponse.token);
            this.navigationService.go(['main']);
        }
 }

LoginEventData gives the following error 
file: 'file:///c%3A/Users/nelson%20william/Groceries/app/pages/login/login.component.ts'
severity: 'Error'
message: 'Namespace '"c:/Users/nelson william/Groceries/node_modules/nativescript-facebook/index"' has no exported member 'LoginEventData'.'
at: '30,30'
source: 'ts'

**Comment by theqaangel** [comment]
@nelsonwilliam11 could you tell me which typescript version you have installed? 
**tsc --version**

**Comment by angeltsvetkov** [comment]
@nelsonwilliam11 could you tell me which typescript version you have installed?
tsc --version

**Comment by nelsonwilliam11** [comment]
my version is 
"typescript": "~2.2.1"

**Comment by angeltsvetkov** [comment]
Cool. I think this is the problem. My suggestion is to update to typescript 2.2.2. Follow next steps:

1. npm uninstall -g typescript
2. nom install -g typescript@2.2.2
3. delete platforms folder of your app
4. tns run

Let me know whether this helps?

**Comment by nelsonwilliam11** [comment]
i upgraded my ts to 2.2.2 and still get the same error

**Comment by angeltsvetkov** [comment]
Alright. I think there is one final step we have to do here. I am very confident that the problem was related to your typescript version (the global one). No what you did I that you updated it to 2.2.2. 
Let's **delete the node_modules folder and again platforms folder of your app** and see whether this is going to help.

**Comment by DimitarTachev** [comment]
@nelsonwilliam11 Could you also confirm that the plugin version in "c:/Users/nelson william/Groceries/node_modules/nativescript-facebook/package.json" is 2.0.0 and what's the way you import Facebook in the problematic file (e.g. import * as Facebook from "nativescript-facebook";)?

**Comment by angeltsvetkov** [comment]
@nelsonwilliam11  I am going to close the issue assuming that you managed to solve your problem. If you still face any impediments please feel free to reopen it or open a new one.
