### ISSUE TITLE
Enable custom text/title on the LoginButton

### ISSUE THREAD

**Issue by ADjenkov** [NativeScript/nativescript-facebook#32]
I think that the `text` property of LoginButton should be taken into account.

<Facebook:LoginButton text="My own Login text" login="onLoginFacebookButtonTap"></Facebook:LoginButton>

**Comment by patrickpereira** [comment]
+1

**Comment by DimitarTachev** [comment]
We support both [the Facebook button recommended and provided by the native iOS and Android Facebook SDKs](https://github.com/NativeScript/nativescript-facebook#facebook-login-button-1) and [a custom user-defined button](https://github.com/NativeScript/nativescript-facebook#custom-login-button-1) as the Facebook native SDKs does not support some customizations like changing the button text programmatically.

Could you provide us with more details about your use cases and if the custom login button flow is applicable to it?

**Comment by DimitarTachev** [comment]
I'm closing this issue as [this behavior is now described in our FAQ section](https://github.com/NativeScript/nativescript-facebook/wiki/FAQ#is-it-possible-to-modify-the-loginbutton-text-using-a-nativescript-property).
