### ISSUE TITLE
Not redirecting back to app iOS

### ISSUE THREAD

**Issue by patrickpereira** [NativeScript/nativescript-facebook#33]
I'm not getting redirected back to the app, whether I choose Cancel or OK, I just get stuck on a blank safari page.

I've added the required config in my plist file, though I had to add the LSApplicationQueriesSchemes in my own plist, as I have LSApplicationQueriesSchemes entries already and NS doesn't merge them.

The app is built for iOS9 and later.

tns info:

All NativeScript components versions information
┌──────────────────┬────────────────────────────┬────────────────┬─────────────┐
│ Component        │ Current version            │ Latest version │ Information │
│ nativescript     │ 3.0.3                      │ 3.0.3          │ Up to date  │
│ tns-core-modules │ 3.1.0-2017-06-01-6770      │ 3.0.1          │ Up to date  │
│ tns-android      │ 3.1.0-next-2017-05-31-1827 │ 3.0.1          │ Up to date  │
│ tns-ios          │ 3.0.1                      │ 3.0.1          │ Up to date  │
└──────────────────┴────────────────────────────┴────────────────┴─────────────┘

plist looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>${PRODUCT_NAME}</string>
	<key>CFBundleExecutable</key>
	<string>${EXECUTABLE_NAME}</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>${PRODUCT_NAME}</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.5.2</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1.5.2</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIRequiresFullScreen</key> 
	<false/> 
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIStatusBarHidden</key>
	<true/>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>NSCalendarsUsageDescription</key>
	<string>Some ad content may access calendar</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>tel</string>
		<string>telprompt</string>
		<string>whatsapp</string>
		<string>fb</string>
		<string>twitter</string>
		<string>gplus</string>
		<string>itms-apps</string>
		<string>itms</string>
		<string>fbapi</string>
		<string>fb-messenger-api</string>
		<string>fbauth2</string>
		<string>fbshareextension</string>
	</array>
	<key>FirebaseAutomaticScreenReportingEnabled</key>
	<false/>
	<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fbXXXXXXXXXXXX</string>
			</array>
		</dict>
	</array>
	<key>FacebookAppID</key>
	<string>XXXXXXXXXXXX</string>
	<key>FacebookDisplayName</key>
	<string>Kcal Life</string>
</dict>
</plist>
```

![simulator screen shot 7 jun 2017 09 47 55](https://user-images.githubusercontent.com/10369669/26863966-aea8ae28-4b66-11e7-8167-b59b207b8c87.png)
![simulator screen shot 7 jun 2017 09 47 59](https://user-images.githubusercontent.com/10369669/26863965-aea63dfa-4b66-11e7-8efd-c2f70310807b.png)

**Comment by patrickpereira** [comment]
There was an issue with another plugin's initialisation

**Comment by Yamilquery** [comment]
What plugin caused the conflict friend?

**Comment by gpfiel** [comment]
@patrickpereira Hi, I am having the same issue. How did you managed to fix it?
