### ISSUE TITLE
[ts] property "logout" does not exist on type "typeof"

### ISSUE THREAD

**Issue by nelsonwilliam11** [NativeScript/nativescript-facebook#35]
logout() {
        Facebook.logout(() => {
            appSettings.clear();
            this.navigationService.go(['login'], "slideRight");
        });
    }}
i dont know what went wrong

**Comment by angeltsvetkov** [comment]
Hey @nelsonwilliam11, is this a snippet from the demo-angular or this is a snippet from your app?

**Comment by nelsonwilliam11** [comment]
From my app

**Comment by angeltsvetkov** [comment]
Could you share the modules you import or require in this file? These should be on the top of the file. Just copy and paste the entire rows here.

**Comment by nelsonwilliam11** [comment]
import { EventData } from "data/observable";
let appSettings = require("application-settings");
import { NavigationService } from  "../../services/navigation.service";
import { RouterExtensions } from "nativescript-angular/router";
import { LoginResponse } from "nativescript-facebook";
import * as Facebook from "nativescript-facebook";

let http = require("http");


import * as application from 'application';
var nsFacebook = require('nativescript-facebook');
import { setHintColor } from "../../utils/hint-util";
import { TextField } from "ui/text-field";
import { Color } from "color";
import { View } from "ui/core/view";
import { Router } from "@angular/router";
import { Page } from "ui/page";
import { Component, ElementRef, OnInit,  ChangeDetectionStrategy, 
  ViewChild, ChangeDetectorRef  } from "@angular/core";
import { User } from "../../shared/user/user";
import { UserService } from "../../shared/user/user.service";

**Comment by DimitarTachev** [comment]
@nelsonwilliam11 Everything is working OK on my side with the same imports and the same logOut usage. I suppose you assign the Facebook variable to something else or the tsconfig is not properly configured and its importing something else (not the nativescript-facebook node module). You could try using the logOut function from the nsFacebook variable (this will ignore the tsconfig issue as its using require).

**Comment by angeltsvetkov** [comment]
I assume that you manage to solve this issue since there is no response from you. I am going to close it. Please feel free to reopen it or open a new one if you face any kind of problems with nativescript-facebook plugin.
