### ISSUE TITLE
Bad reference to "data/observable"

### ISSUE THREAD

**Issue by Yamilquery** [NativeScript/nativescript-facebook#36]
They have a reference error in their plugin. Which does not allow compiling with WebPack AoT

This is the solution:

On **login-event-data.d.ts**

`import { EventData } from "data/observable";`

Replace By

`import { EventData } from "tns-core-modules/data/observable";`

On **login-button.d.ts:**

`import { EventData } from "data/observable";`

By:

`import { EventData } from "tns-core-modules/data/observable";`

I hope they can merge to master branch soon.

Thank you!

**Comment by Yamilquery** [comment]
I am not sure if it has to do with the reference that I have changed, but pressing the Login button will freeze the app and do not send any errors in console.

**Comment by angeltsvetkov** [comment]
Hey @Yamilquery, thanks for reporting this issue. I need to investigate it further. 
We are open for any kind of improvements or fixes so do not hesitate to make a pull request.

**Comment by angeltsvetkov** [comment]
Hey @Yamilquery, 
Could you check out the latest version of nativescript-facebook plugin? It should contain the fixes you mentioned. We incorporated checks that assure that the plugin is webpack compatible for NativeScript angular apps as well as NativeScript Core apps.
Let us know if you still have such an issue.

**Comment by angeltsvetkov** [comment]
Hi @Yamilquery,
I assume you are OK with the applied fix. Please feel free to let us know if you find any other related issues.
