### ISSUE TITLE
How to get email or user_profile after sign in facebook

### ISSUE THREAD

**Issue by yclau** [NativeScript/nativescript-facebook#41]
Hi ,
I success login the Facebook using this plugin, but how I get email or user profile? 
I already follow the instruction to added scrope in app.js. 
```
var facebookInitOptions = tnsOAuthModule.ITnsOAuthOptionsFacebook = {
        clientId: '111',
        clientSecret: '1111',
        scope: ['public_profile','email'] //whatever other scopes you need
    };

tnsOAuthModule.initFacebook(facebookInitOptions);
```

**Comment by angeltsvetkov** [comment]
Hey @yclau,
Great to hear you managed to configure nativescript-facebook plugin. Did you check out the [readme section](https://github.com/NativeScript/nativescript-facebook#graph-api-example) where we have an example how to use [Facebook Graph API](https://developers.facebook.com/docs/graph-api)? This example demonstrates how to retrieve the facebook id of the logged in user and also how to get his/her avatar. It should be quite easy to retrieve the email as well. 

You can also refer to this issue where @98falcon proposed an improvement and retrieve all the required data with just one API call.

Please let me know if you still have any issues with this!

**Comment by angeltsvetkov** [comment]
Hi @yclau. I assume you managed to solve the issue after my explanations. Please feel free to reopen it or open a new one if you face any problems using NativeScript Facebook plugin.
