### ISSUE TITLE
Are there any plans to implement getLoginStatus()?

### ISSUE THREAD

**Issue by NishadKulk** [NativeScript/nativescript-facebook#43]
Hello,

On the facebook javascript sdk as well as android sdk, there is a way to check whether a user is already logged in (e.g. to decide whether to take them to the login screen). Is there currently any plan to implement this?

At the moment I can crudely mimic this by making a graph API call with a saved token to see if it succeeds, but built in functionality would be very useful.

Thank you!

**Comment by DimitarTachev** [comment]
Hi,

Thank you for your feedback. As far as I see the getLoginStatus method is available in the JS SDK but it is not available in the native versions of the Android and iOS SDKs used in this plugin.

However, it is a very nice idea and we will definitely think about exposing such method in the plugin using the available workarounds of the Android and iOS SDKs internally.

I have already added this issue in our 2.1.0 Milestone which most probably will be our next release.

**Comment by NishadKulk** [comment]
Thank you very much!

**Comment by tbozhikov** [comment]
#85 PR provides a way to get the current access token, and can be used to get the login status:
   - if null => not logged in
   - if FacebookAccessToken object => logged in
