### ISSUE TITLE
Facebook Account Kit integration

### ISSUE THREAD

**Issue by albe-rosado** [NativeScript/nativescript-facebook#50]
Would be nice if we could get Account Kit integration in the plugin as well. I would love to contribute. React Native have it  [already](https://github.com/underscopeio/react-native-facebook-account-kit).

**Comment by angeltsvetkov** [comment]
Hi @albe-rosado, this sounds like a great idea. Do you think that Facebook Account Kit should be incorporated in this plugin? How about separate plugin for Facebook Account Kit?

**Comment by henrique1977** [comment]
I'm also interested in a plugin for the Facebook Account Kit. Maybe as a separate plugin would be nice.

**Comment by pushkardeshmukh1992** [comment]
+1

**Comment by strebl** [comment]
Another plugin would be fantastic.

**Comment by kambojaz** [comment]
+1

**Comment by velchev** [comment]
Another plugin... not done yet, I guess... will have to dig and do it ourselves 👍

**Comment by radeva** [comment]
@velchev You can use the [plugin seed](https://github.com/NativeScript/nativescript-plugin-seed) as a starting point:)

**Comment by rajivnarayana** [comment]
In the making, 
https://github.com/rajivnarayana/nativescript-facebook-account-kit.
https://www.npmjs.com/package/nativescript-facebook-account-kit.
@radeva, Did use the plugin seed as a starting point. 

Ran into issues where I could not set properties on iOS for and had to `[NSObject performObjectWithSelector]` and `[NSInvocation invocationWithMethodSignature]` etc. Resolved them and am successfully able to receive code to phone and eventually get an auth code.

Would some body like to contribute? I can bring in simple UI customization by myself but I would like to have contributions to support advanced UI via {N}.
@albe-rosado?
