### ISSUE TITLE
Error: The operation couldn’t be completed. (com.facebook.sdk.core error 3.)

### ISSUE THREAD

**Issue by bonlemuel** [NativeScript/nativescript-facebook#55]
Hi! Great Nativescript plugin! I've managed to follow all guide. But I'm getting this error. Did I miss something? Thanks!

**Comment by angeltsvetkov** [comment]
Hi, @bonlemuel. I am sorry for the problem you experienced with nativescript-facebook plugin. Could you share for which platform (Android/iOS) you faced this issue? Also, whether your NativeScript app is Angular or not? Did you manage to build and run any of the demo apps?

**Comment by bonlemuel** [comment]
It runs on Angular. I'm currently testing it on iOS. But I've managed to solved the issue by adding the code below.

```
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fbxxxxxxxxxxxxxxxxx</string>
			</array>
		</dict>
	</array>
	<key>FacebookAppID</key>
		<string>{AppID}</string>
	<key>FacebookDisplayName</key>
		<string>{AppName}</string>
<key>LSApplicationQueriesSchemes</key>
<array>
	<string>fbauth2</string>
	<string>fbapi</string>
	<string>fb-messenger-api</string>
	<string>fbshareextension</string>
</array>
```

Thank you.

**Comment by angeltsvetkov** [comment]
Awesome!
