### ISSUE TITLE
onLogin callback not called 

### ISSUE THREAD

**Issue by jorotenev** [NativeScript/nativescript-facebook#59]
Ahoy
I used `tns create --tsc` to provision a basic HelloWorld app. After installing the plugin, I followed the instructions from the README by adding the login-view.[ts|xml] + login-view-model.ts and updating the app.ts ([here's](https://github.com/jorotenev/ns-fb-demo) a repo with the code). 
I set up a temp FB app and got my app id. After starting the app and logging into Facebook, the `onLogin` callback in `login-view-model.ts` is never called (I don't see any console.logs in the terminal). The view is not changed (it's still the login-view), however the button says Log out now and pressing it asks for confirmation if i want to log out (it states my name too).

![screenshot from 2017-08-10 22-46-52](https://user-images.githubusercontent.com/8976783/29191389-d939a22a-7e1d-11e7-8141-de887135b97a.png)

I realise I might have screwed up my fb settings (i followed the Facebook Login Quickstart for Android and added the name of the main app activity, the app name & dev hash keys). I guess it would be useful to point to a tutorial on how to do that if the quickstart is not sufficient :)

Cheers

**Comment by angeltsvetkov** [comment]
Hi @jorotenev. Could you double check where you navigate after successful login. As I can see - home-view. Unfortunately, you do not have such a component in your app. It is called main-view. Also you didn't register them appropriately in the bundle-config file. My suggestion is to start your app from native-script-facebook demo app instead of hello-world app. It is configured appropriately.

**Comment by jorotenev** [comment]
Thanks for the reply
I updated the repo from the first post.
* included the bundle file from the demo here to my project
* added the `app.config.ts`
* added the `home-page.[ts|xml]` files
* added the `vendor.x` files
* removed the `node_modules` and re-ran `tns run android`

The result is exactly the same. I got the demo from here running but I'd prefer to understand where I'm going wrong when using the hello world template :)


Thanks for your time :)

**Comment by jorotenev** [comment]
my bad. apologies.
I did a `diff` b/w my project and the demo and saw that i named `login-page.ts`  as `login-view.ts`.
