### ISSUE TITLE
License: MIT or Apache 2.0

### ISSUE THREAD

**Issue by EddyVerbruggen** [NativeScript/nativescript-facebook#7]
The [LICENSE file](https://github.com/NativeScript/nativescript-facebook/blob/7add75280404537e0049a5d82c435408ce608597/LICENSE) is Apache 2.0, but [package.json](https://github.com/NativeScript/nativescript-facebook/blob/7add75280404537e0049a5d82c435408ce608597/src/package.json#L45) says "MIT". Which one is correct? 🤔

**Comment by angeltsvetkov** [comment]
Right! 
Any preferences?

**Comment by EddyVerbruggen** [comment]
I always use MIT, but I noticed most NativeScript packages use Apache 2.0 so I guess it makes sense to use whatever all other NativeScript assets do. There's probably someone within the company that decides which license should be used so you may want to check that internally :)

**Comment by angeltsvetkov** [comment]
Updated [https://github.com/NativeScript/nativescript-facebook/pull/12/files](url)
