### ISSUE TITLE
Add scope to login method

### ISSUE THREAD

**Issue by arcovoltaico** [NativeScript/nativescript-facebook#84]
I think the login method should include the scope options, as the official API do:
FB.login(function(response) {
   console.log(response);
}, {scope: 'email, 'user_friends'});

Is it possible?
Thanks

**Comment by tbozhikov** [comment]
Hi @arcovoltaico, #75 addresses this matter. In short, the Facebook-recommended way is to ask for permissions just before you need them, not at logging in: https://github.com/NativeScript/nativescript-facebook/issues/75#issuecomment-351111664

**Comment by tbozhikov** [comment]
I'm closing this, please re-open if you have further questions.
