### ISSUE TITLE
doc: LSApplicationQueriesSchemes and is required for iOS 9.0+

### ISSUE THREAD

**Issue by vbresults** [NativeScript/nativescript-facebook#9]
@angeltsvetkov

```text
<Notice>: *** Terminating app due to uncaught exception 'InvalidOperationException', reason: 'fbauth2 is missing from your Info.plist under LSApplicationQueriesSchemes and is required for iOS 9.0'
```

**Comment by angeltsvetkov** [comment]
Interesting.
If you look at [here](https://github.com/NativeScript/nativescript-facebook/blob/master/src/platforms/ios/Info.plist#L12) you will see that fbauth2 is part of the LSApplicationQueriesSchemes. 
NativeScript CLI merges this Info.plist with your project Info.plist file (more info [here](http://docs.nativescript.org/plugins/plugins)) so finally it should be in your pList file.
Just to be sure, did you add the required configurations as described in the [REAME file](https://github.com/NativeScript/nativescript-facebook#configuration)?

**Comment by vbresults** [comment]
I do have the required configuration.  It did not merge the scheme.  Perhaps because I already had an LSApplicationQueriesSchemes entry and the NS merger doesn't handle recursion properly.

**Comment by angeltsvetkov** [comment]
Could you share your app Info.plist file?

**Comment by angeltsvetkov** [comment]
I will close this since there is no response. Feel free to reopen it if you can provide more details!
