### ISSUE TITLE
Missing productFlavors on published version on npm 2.2.1 

### ISSUE THREAD

**Issue by hiperbou** [NativeScript/nativescript-facebook#91]
On the published version on npm 2.2.1 productFlavors is missing in the include.gradle.
This causes a compilation error when trying to build an app.

### Please, tell us how to recreate the issue in as much detail as possible. 
npm install nativescript-facebook

Open node_modules/nativescript-facebook/platforms/android/include.gradle and notice the missing configuration.

**Comment by DimitarTodorov** [comment]
Hello hiperbou,

These properties are not needed in the latest official versions of the NativeScript CLI and Android Runtime (tns@3.4.3 and tns-android:3.4.2). Can You please tell us more about your configuration of the NativeScript runtime for Android and CLI versions.

Thanks,
Dimitar

**Comment by hiperbou** [comment]
I'm using tns@3.3.1 and tns-android:3.3.1 

I'll stick with version 2.2.0 for now.
Thanks.
