### ISSUE TITLE
App rejected by Apple because "using Safari" to log FB

### ISSUE THREAD

**Issue by arcovoltaico** [NativeScript/nativescript-facebook#93]
Today I got my app rejected:
"We noticed that the user is taken to Safari to sign in or register for an account, which provides a poor user experience."

Is anything I can change from my side? It seems crazy ...
Thanks!

<img width="376" alt="captura de pantalla 2018-03-23 a las 16 38 00" src="https://user-images.githubusercontent.com/4580198/37849251-41df9176-2ed7-11e8-94cc-a28c26e94b3a.png">
<img width="362" alt="captura de pantalla 2018-03-23 a las 16 38 06" src="https://user-images.githubusercontent.com/4580198/37849252-41fba5f0-2ed7-11e8-8001-ceb242a1db00.png">

**Comment by arcovoltaico** [comment]
Although I'd like to know how to set the behavior on Angular Typescript,  a fast fix is in
login.manager.ios.js

On Line 9
change 
 if (fbLoginBehavior === void 0) { fbLoginBehavior = login_behavior_1.LoginBehavior.LoginBehaviorBrowser; }

to
  if (fbLoginBehavior === void 0) { fbLoginBehavior = login_behavior_1.LoginBehavior.LoginBehaviorNative; }

**Comment by DimitarTachev** [comment]
Hi @arcovoltaico,

Just pass the desired LoginBehavior as [a second parameter to the `init` method of the plugin](https://github.com/NativeScript/nativescript-facebook/blob/5149c1db52f59869a07c33393acd84eac35ccba2/src/login-manager.ios.ts#L23) (`LoginBehaviorBrowser` is the `default value`).

```
...
import { LoginBehavior } from "nativescript-facebook";
...
nsFacebook.init("fb_id", LoginBehavior.LoginBehaviorNative);
...
```

**Comment by arcovoltaico** [comment]
Thanks so much !
